DROP TABLE public.songs;
DROP TABLE public.users;
DROP TABLE public.song_songlist;
DROP TABLE public.songlist;


CREATE TABLE public.songs
(
	id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1)  UNIQUE PRIMARY KEY,
	title VARCHAR(100) not null,
	artist VARCHAR(100) not null,
	label VARCHAR(100),
	released INT
);


CREATE TABLE public.users
(
	userId VARCHAR(50) NOT NULL PRIMARY KEY ,
	password VARCHAR(50) not null,
	firstName VARCHAR(50) not null,
	lastName VARCHAR(50)
);




CREATE TABLE public.songlist
(
	id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1)  UNIQUE PRIMARY KEY,
	ownerid VARCHAR(100) not null,
	name VARCHAR(100),
	isPrivate bool
);

CREATE TABLE public.song_songlist
(
    song_id integer,
    list_id integer,
    FOREIGN KEY (song_id)
        REFERENCES public.songs (id),
    FOREIGN KEY (list_id)
        REFERENCES songlist (id)

);

INSERT INTO public.songs(userId, password, firstName, lastName) VALUES ('eschuler', 'pass1234', 'First', 'Last');
INSERT INTO public.users(userId, password, firstName, lastName) VALUES ('mmuster', 'pass1234', 'First', 'Last');